// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ingest/v1/ingest.proto

package ingestv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Field is a structured key/value pair on a LogEntry. value_json is the
// JSON encoding of the original value (a number, bool, string, or
// nested object) rather than a plain string field, so arbitrary field
// types survive the wire the same way they do over the REST/WebSocket
// ingestion paths — proto3 has no "any-typed" scalar, and adding
// google.protobuf.Struct/Value here would pull in the well-known-types
// dependency for what a plain string round-trips just as well.
type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ValueJson     string                 `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_ingest_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_ingest_v1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *Field) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Field) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

type LogEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixNano int64                  `protobuf:"varint,1,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	Level             string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Fields            []*Field               `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_ingest_v1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_v1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_ingest_v1_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntry) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type IngestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// source tags who's pushing this entry — shown in logGO's UI as the
	// source badge, same as an entry ingested by pulling from a remote
	// instance (internal/ingest), just pushed instead of pulled.
	Source        string    `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Entry         *LogEntry `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_ingest_v1_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_v1_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_ingest_v1_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *IngestRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IngestRequest) GetEntry() *LogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_ingest_v1_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_v1_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_ingest_v1_ingest_proto_rawDescGZIP(), []int{3}
}

var File_ingest_v1_ingest_proto protoreflect.FileDescriptor

const file_ingest_v1_ingest_proto_rawDesc = "" +
	"\n" +
	"\x16ingest/v1/ingest.proto\x12\tingest.v1\"8\n" +
	"\x05Field\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\tR\tvalueJson\"\x94\x01\n" +
	"\bLogEntry\x12.\n" +
	"\x13timestamp_unix_nano\x18\x01 \x01(\x03R\x11timestampUnixNano\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12(\n" +
	"\x06fields\x18\x04 \x03(\v2\x10.ingest.v1.FieldR\x06fields\"R\n" +
	"\rIngestRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12)\n" +
	"\x05entry\x18\x02 \x01(\v2\x13.ingest.v1.LogEntryR\x05entry\"\x10\n" +
	"\x0eIngestResponse2N\n" +
	"\rIngestService\x12=\n" +
	"\x06Ingest\x12\x18.ingest.v1.IngestRequest\x1a\x19.ingest.v1.IngestResponseB?Z=github.com/ttfancy/logGO/internal/genproto/ingest/v1;ingestv1b\x06proto3"

var (
	file_ingest_v1_ingest_proto_rawDescOnce sync.Once
	file_ingest_v1_ingest_proto_rawDescData []byte
)

func file_ingest_v1_ingest_proto_rawDescGZIP() []byte {
	file_ingest_v1_ingest_proto_rawDescOnce.Do(func() {
		file_ingest_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingest_v1_ingest_proto_rawDesc), len(file_ingest_v1_ingest_proto_rawDesc)))
	})
	return file_ingest_v1_ingest_proto_rawDescData
}

var file_ingest_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ingest_v1_ingest_proto_goTypes = []any{
	(*Field)(nil),          // 0: ingest.v1.Field
	(*LogEntry)(nil),       // 1: ingest.v1.LogEntry
	(*IngestRequest)(nil),  // 2: ingest.v1.IngestRequest
	(*IngestResponse)(nil), // 3: ingest.v1.IngestResponse
}
var file_ingest_v1_ingest_proto_depIdxs = []int32{
	0, // 0: ingest.v1.LogEntry.fields:type_name -> ingest.v1.Field
	1, // 1: ingest.v1.IngestRequest.entry:type_name -> ingest.v1.LogEntry
	2, // 2: ingest.v1.IngestService.Ingest:input_type -> ingest.v1.IngestRequest
	3, // 3: ingest.v1.IngestService.Ingest:output_type -> ingest.v1.IngestResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ingest_v1_ingest_proto_init() }
func file_ingest_v1_ingest_proto_init() {
	if File_ingest_v1_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingest_v1_ingest_proto_rawDesc), len(file_ingest_v1_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingest_v1_ingest_proto_goTypes,
		DependencyIndexes: file_ingest_v1_ingest_proto_depIdxs,
		MessageInfos:      file_ingest_v1_ingest_proto_msgTypes,
	}.Build()
	File_ingest_v1_ingest_proto = out.File
	file_ingest_v1_ingest_proto_goTypes = nil
	file_ingest_v1_ingest_proto_depIdxs = nil
}
